# Form implementation generated from reading ui file 'Resources\ui_files\widgets\object_settings_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ObjectSettingsWidget:
    def setupUi(self, ObjectSettingsWidget):
        ObjectSettingsWidget.setObjectName("ObjectSettingsWidget")
        ObjectSettingsWidget.resize(403, 1407)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            ObjectSettingsWidget.sizePolicy().hasHeightForWidth()
        )
        ObjectSettingsWidget.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ObjectSettingsWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.core_settings_vbox = QtWidgets.QVBoxLayout()
        self.core_settings_vbox.setObjectName("core_settings_vbox")
        self.label = QtWidgets.QLabel(ObjectSettingsWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.core_settings_vbox.addWidget(self.label)
        self.enable_download_checkbox = QtWidgets.QCheckBox(ObjectSettingsWidget)
        self.enable_download_checkbox.setObjectName("enable_download_checkbox")
        self.core_settings_vbox.addWidget(self.enable_download_checkbox)
        self.verticalLayout.addLayout(self.core_settings_vbox)
        self.line = QtWidgets.QFrame(ObjectSettingsWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.post_download_form = QtWidgets.QFormLayout()
        self.post_download_form.setObjectName("post_download_form")
        self.line_2 = QtWidgets.QFrame(ObjectSettingsWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.post_download_form.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.line_2
        )
        self.label_19 = QtWidgets.QLabel(ObjectSettingsWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter
        )
        self.label_19.setObjectName("label_19")
        self.post_download_form.setWidget(
            1, QtWidgets.QFormLayout.SpanningRole, self.label_19
        )
        self.label_30 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_30.setObjectName("label_30")
        self.post_download_form.setWidget(
            14, QtWidgets.QFormLayout.LabelRole, self.label_30
        )
        self.extract_self_post_content_checkbox = QtWidgets.QCheckBox(
            ObjectSettingsWidget
        )
        self.extract_self_post_content_checkbox.setText("")
        self.extract_self_post_content_checkbox.setObjectName(
            "extract_self_post_content_checkbox"
        )
        self.post_download_form.setWidget(
            14, QtWidgets.QFormLayout.FieldRole, self.extract_self_post_content_checkbox
        )
        self.label_15 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_15.setObjectName("label_15")
        self.post_download_form.setWidget(
            15, QtWidgets.QFormLayout.LabelRole, self.label_15
        )
        self.download_self_post_text_checkbox = QtWidgets.QCheckBox(
            ObjectSettingsWidget
        )
        self.download_self_post_text_checkbox.setText("")
        self.download_self_post_text_checkbox.setObjectName(
            "download_self_post_text_checkbox"
        )
        self.post_download_form.setWidget(
            15, QtWidgets.QFormLayout.FieldRole, self.download_self_post_text_checkbox
        )
        self.label_31 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_31.setObjectName("label_31")
        self.post_download_form.setWidget(
            16, QtWidgets.QFormLayout.LabelRole, self.label_31
        )
        self.self_post_file_format_combo = QtWidgets.QComboBox(ObjectSettingsWidget)
        self.self_post_file_format_combo.setObjectName("self_post_file_format_combo")
        self.post_download_form.setWidget(
            16, QtWidgets.QFormLayout.FieldRole, self.self_post_file_format_combo
        )
        self.label_13 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_13.setObjectName("label_13")
        self.post_download_form.setWidget(
            17, QtWidgets.QFormLayout.LabelRole, self.label_13
        )
        self.download_videos_checkbox = QtWidgets.QCheckBox(ObjectSettingsWidget)
        self.download_videos_checkbox.setText("")
        self.download_videos_checkbox.setObjectName("download_videos_checkbox")
        self.post_download_form.setWidget(
            17, QtWidgets.QFormLayout.FieldRole, self.download_videos_checkbox
        )
        self.label_14 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_14.setObjectName("label_14")
        self.post_download_form.setWidget(
            18, QtWidgets.QFormLayout.LabelRole, self.label_14
        )
        self.download_images_checkbox = QtWidgets.QCheckBox(ObjectSettingsWidget)
        self.download_images_checkbox.setText("")
        self.download_images_checkbox.setObjectName("download_images_checkbox")
        self.post_download_form.setWidget(
            18, QtWidgets.QFormLayout.FieldRole, self.download_images_checkbox
        )
        self.label_29 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_29.setObjectName("label_29")
        self.post_download_form.setWidget(
            19, QtWidgets.QFormLayout.LabelRole, self.label_29
        )
        self.download_gifs_checkbox = QtWidgets.QCheckBox(ObjectSettingsWidget)
        self.download_gifs_checkbox.setText("")
        self.download_gifs_checkbox.setObjectName("download_gifs_checkbox")
        self.post_download_form.setWidget(
            19, QtWidgets.QFormLayout.FieldRole, self.download_gifs_checkbox
        )
        self.label_28 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_28.setObjectName("label_28")
        self.post_download_form.setWidget(
            20, QtWidgets.QFormLayout.LabelRole, self.label_28
        )
        self.nsfw_filter_combo = QtWidgets.QComboBox(ObjectSettingsWidget)
        self.nsfw_filter_combo.setObjectName("nsfw_filter_combo")
        self.post_download_form.setWidget(
            20, QtWidgets.QFormLayout.FieldRole, self.nsfw_filter_combo
        )
        self.post_download_naming_label = QtWidgets.QLabel(ObjectSettingsWidget)
        self.post_download_naming_label.setObjectName("post_download_naming_label")
        self.post_download_form.setWidget(
            22, QtWidgets.QFormLayout.LabelRole, self.post_download_naming_label
        )
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.post_download_naming_line_edit = QtWidgets.QLineEdit(ObjectSettingsWidget)
        self.post_download_naming_line_edit.setObjectName(
            "post_download_naming_line_edit"
        )
        self.horizontalLayout_2.addWidget(self.post_download_naming_line_edit)
        self.post_download_naming_available_tokens_button = QtWidgets.QToolButton(
            ObjectSettingsWidget
        )
        self.post_download_naming_available_tokens_button.setObjectName(
            "post_download_naming_available_tokens_button"
        )
        self.horizontalLayout_2.addWidget(
            self.post_download_naming_available_tokens_button
        )
        self.post_download_form.setLayout(
            22, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2
        )
        self.post_save_structure_label = QtWidgets.QLabel(ObjectSettingsWidget)
        self.post_save_structure_label.setObjectName("post_save_structure_label")
        self.post_download_form.setWidget(
            23, QtWidgets.QFormLayout.LabelRole, self.post_save_structure_label
        )
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.post_save_path_structure_line_edit = QtWidgets.QLineEdit(
            ObjectSettingsWidget
        )
        self.post_save_path_structure_line_edit.setObjectName(
            "post_save_path_structure_line_edit"
        )
        self.horizontalLayout_5.addWidget(self.post_save_path_structure_line_edit)
        self.post_save_structure_available_tokens_button = QtWidgets.QToolButton(
            ObjectSettingsWidget
        )
        self.post_save_structure_available_tokens_button.setObjectName(
            "post_save_structure_available_tokens_button"
        )
        self.horizontalLayout_5.addWidget(
            self.post_save_structure_available_tokens_button
        )
        self.post_download_form.setLayout(
            23, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5
        )
        self.duplicate_controls_groupbox = QtWidgets.QGroupBox(ObjectSettingsWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.duplicate_controls_groupbox.setFont(font)
        self.duplicate_controls_groupbox.setFlat(False)
        self.duplicate_controls_groupbox.setObjectName("duplicate_controls_groupbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.duplicate_controls_groupbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.duplicate_controls_layout = QtWidgets.QFormLayout()
        self.duplicate_controls_layout.setObjectName("duplicate_controls_layout")
        self.avoid_duplicate_urls_label = QtWidgets.QLabel(
            self.duplicate_controls_groupbox
        )
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.avoid_duplicate_urls_label.setFont(font)
        self.avoid_duplicate_urls_label.setObjectName("avoid_duplicate_urls_label")
        self.duplicate_controls_layout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.avoid_duplicate_urls_label
        )
        self.hash_content_label = QtWidgets.QLabel(self.duplicate_controls_groupbox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.hash_content_label.setFont(font)
        self.hash_content_label.setObjectName("hash_content_label")
        self.duplicate_controls_layout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.hash_content_label
        )
        self.avoid_duplicates_checkbox = QtWidgets.QCheckBox(
            self.duplicate_controls_groupbox
        )
        self.avoid_duplicates_checkbox.setText("")
        self.avoid_duplicates_checkbox.setObjectName("avoid_duplicates_checkbox")
        self.duplicate_controls_layout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.avoid_duplicates_checkbox
        )
        self.hash_content_checkbox = QtWidgets.QCheckBox(
            self.duplicate_controls_groupbox
        )
        self.hash_content_checkbox.setText("")
        self.hash_content_checkbox.setObjectName("hash_content_checkbox")
        self.duplicate_controls_layout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.hash_content_checkbox
        )
        self.duplicate_control_method_combo_label = QtWidgets.QLabel(
            self.duplicate_controls_groupbox
        )
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.duplicate_control_method_combo_label.setFont(font)
        self.duplicate_control_method_combo_label.setObjectName(
            "duplicate_control_method_combo_label"
        )
        self.duplicate_controls_layout.setWidget(
            2,
            QtWidgets.QFormLayout.LabelRole,
            self.duplicate_control_method_combo_label,
        )
        self.duplicate_control_method_combo = QtWidgets.QComboBox(
            self.duplicate_controls_groupbox
        )
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.duplicate_control_method_combo.setFont(font)
        self.duplicate_control_method_combo.setObjectName(
            "duplicate_control_method_combo"
        )
        self.duplicate_controls_layout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.duplicate_control_method_combo
        )
        self.duplicate_naming_method_label = QtWidgets.QLabel(
            self.duplicate_controls_groupbox
        )
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.duplicate_naming_method_label.setFont(font)
        self.duplicate_naming_method_label.setObjectName(
            "duplicate_naming_method_label"
        )
        self.duplicate_controls_layout.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.duplicate_naming_method_label
        )
        self.duplicate_naming_method_layout = QtWidgets.QHBoxLayout()
        self.duplicate_naming_method_layout.setSpacing(2)
        self.duplicate_naming_method_layout.setObjectName(
            "duplicate_naming_method_layout"
        )
        self.duplicate_naming_line_edit = QtWidgets.QLineEdit(
            self.duplicate_controls_groupbox
        )
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.duplicate_naming_line_edit.setFont(font)
        self.duplicate_naming_line_edit.setObjectName("duplicate_naming_line_edit")
        self.duplicate_naming_method_layout.addWidget(self.duplicate_naming_line_edit)
        self.duplicate_naming_available_tokens_button = QtWidgets.QToolButton(
            self.duplicate_controls_groupbox
        )
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.duplicate_naming_available_tokens_button.setFont(font)
        self.duplicate_naming_available_tokens_button.setObjectName(
            "duplicate_naming_available_tokens_button"
        )
        self.duplicate_naming_method_layout.addWidget(
            self.duplicate_naming_available_tokens_button
        )
        self.duplicate_controls_layout.setLayout(
            3, QtWidgets.QFormLayout.FieldRole, self.duplicate_naming_method_layout
        )
        self.duplicate_save_structure_label = QtWidgets.QLabel(
            self.duplicate_controls_groupbox
        )
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.duplicate_save_structure_label.setFont(font)
        self.duplicate_save_structure_label.setObjectName(
            "duplicate_save_structure_label"
        )
        self.duplicate_controls_layout.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.duplicate_save_structure_label
        )
        self.duplicate_save_structure_layout = QtWidgets.QHBoxLayout()
        self.duplicate_save_structure_layout.setSpacing(2)
        self.duplicate_save_structure_layout.setObjectName(
            "duplicate_save_structure_layout"
        )
        self.duplicate_save_structure_line_edit = QtWidgets.QLineEdit(
            self.duplicate_controls_groupbox
        )
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.duplicate_save_structure_line_edit.setFont(font)
        self.duplicate_save_structure_line_edit.setObjectName(
            "duplicate_save_structure_line_edit"
        )
        self.duplicate_save_structure_layout.addWidget(
            self.duplicate_save_structure_line_edit
        )
        self.duplicate_save_structure_available_tokens_button = QtWidgets.QToolButton(
            self.duplicate_controls_groupbox
        )
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.duplicate_save_structure_available_tokens_button.setFont(font)
        self.duplicate_save_structure_available_tokens_button.setObjectName(
            "duplicate_save_structure_available_tokens_button"
        )
        self.duplicate_save_structure_layout.addWidget(
            self.duplicate_save_structure_available_tokens_button
        )
        self.duplicate_controls_layout.setLayout(
            4, QtWidgets.QFormLayout.FieldRole, self.duplicate_save_structure_layout
        )
        self.verticalLayout_3.addLayout(self.duplicate_controls_layout)
        self.post_download_form.setWidget(
            11, QtWidgets.QFormLayout.SpanningRole, self.duplicate_controls_groupbox
        )
        self.verticalLayout.addLayout(self.post_download_form)
        self.line_3 = QtWidgets.QFrame(ObjectSettingsWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.comment_download_form = QtWidgets.QFormLayout()
        self.comment_download_form.setObjectName("comment_download_form")
        self.label_20 = QtWidgets.QLabel(ObjectSettingsWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.comment_download_form.setWidget(
            0, QtWidgets.QFormLayout.SpanningRole, self.label_20
        )
        self.label_32 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_32.setObjectName("label_32")
        self.comment_download_form.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.label_32
        )
        self.comment_extract_combo = QtWidgets.QComboBox(ObjectSettingsWidget)
        self.comment_extract_combo.setObjectName("comment_extract_combo")
        self.comment_download_form.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.comment_extract_combo
        )
        self.label_22 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_22.setObjectName("label_22")
        self.comment_download_form.setWidget(
            3, QtWidgets.QFormLayout.LabelRole, self.label_22
        )
        self.comment_download_combo = QtWidgets.QComboBox(ObjectSettingsWidget)
        self.comment_download_combo.setObjectName("comment_download_combo")
        self.comment_download_form.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.comment_download_combo
        )
        self.label_21 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_21.setObjectName("label_21")
        self.comment_download_form.setWidget(
            4, QtWidgets.QFormLayout.LabelRole, self.label_21
        )
        self.comment_content_download_combo = QtWidgets.QComboBox(ObjectSettingsWidget)
        self.comment_content_download_combo.setObjectName(
            "comment_content_download_combo"
        )
        self.comment_download_form.setWidget(
            4, QtWidgets.QFormLayout.FieldRole, self.comment_content_download_combo
        )
        self.label_23 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_23.setObjectName("label_23")
        self.comment_download_form.setWidget(
            5, QtWidgets.QFormLayout.LabelRole, self.label_23
        )
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comment_limit_spinbox = QtWidgets.QSpinBox(ObjectSettingsWidget)
        self.comment_limit_spinbox.setMaximum(10000)
        self.comment_limit_spinbox.setObjectName("comment_limit_spinbox")
        self.horizontalLayout_4.addWidget(self.comment_limit_spinbox)
        self.comment_limit_max_button = QtWidgets.QToolButton(ObjectSettingsWidget)
        self.comment_limit_max_button.setObjectName("comment_limit_max_button")
        self.horizontalLayout_4.addWidget(self.comment_limit_max_button)
        self.comment_download_form.setLayout(
            5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4
        )
        self.label_3 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_3.setObjectName("label_3")
        self.comment_download_form.setWidget(
            6, QtWidgets.QFormLayout.LabelRole, self.label_3
        )
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comment_depth_spinbox = QtWidgets.QSpinBox(ObjectSettingsWidget)
        self.comment_depth_spinbox.setMaximum(9999)
        self.comment_depth_spinbox.setObjectName("comment_depth_spinbox")
        self.horizontalLayout.addWidget(self.comment_depth_spinbox)
        self.comment_depth_max_button = QtWidgets.QToolButton(ObjectSettingsWidget)
        self.comment_depth_max_button.setObjectName("comment_depth_max_button")
        self.horizontalLayout.addWidget(self.comment_depth_max_button)
        self.comment_download_form.setLayout(
            6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout
        )
        self.label_4 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_4.setObjectName("label_4")
        self.comment_download_form.setWidget(
            7, QtWidgets.QFormLayout.LabelRole, self.label_4
        )
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.comment_reply_limit_spinbox = QtWidgets.QSpinBox(ObjectSettingsWidget)
        self.comment_reply_limit_spinbox.setMaximum(9999)
        self.comment_reply_limit_spinbox.setObjectName("comment_reply_limit_spinbox")
        self.horizontalLayout_8.addWidget(self.comment_reply_limit_spinbox)
        self.comment_reply_max_button = QtWidgets.QToolButton(ObjectSettingsWidget)
        self.comment_reply_max_button.setObjectName("comment_reply_max_button")
        self.horizontalLayout_8.addWidget(self.comment_reply_max_button)
        self.comment_download_form.setLayout(
            7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8
        )
        self.label_2 = QtWidgets.QLabel(ObjectSettingsWidget)
        self.label_2.setObjectName("label_2")
        self.comment_download_form.setWidget(
            13, QtWidgets.QFormLayout.LabelRole, self.label_2
        )
        self.comment_file_format_combo = QtWidgets.QComboBox(ObjectSettingsWidget)
        self.comment_file_format_combo.setObjectName("comment_file_format_combo")
        self.comment_download_form.setWidget(
            13, QtWidgets.QFormLayout.FieldRole, self.comment_file_format_combo
        )
        self.comment_download_naming_label = QtWidgets.QLabel(ObjectSettingsWidget)
        self.comment_download_naming_label.setObjectName(
            "comment_download_naming_label"
        )
        self.comment_download_form.setWidget(
            14, QtWidgets.QFormLayout.LabelRole, self.comment_download_naming_label
        )
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.comment_download_naming_line_edit = QtWidgets.QLineEdit(
            ObjectSettingsWidget
        )
        self.comment_download_naming_line_edit.setObjectName(
            "comment_download_naming_line_edit"
        )
        self.horizontalLayout_6.addWidget(self.comment_download_naming_line_edit)
        self.comment_download_naming_available_tokens_button = QtWidgets.QToolButton(
            ObjectSettingsWidget
        )
        self.comment_download_naming_available_tokens_button.setObjectName(
            "comment_download_naming_available_tokens_button"
        )
        self.horizontalLayout_6.addWidget(
            self.comment_download_naming_available_tokens_button
        )
        self.comment_download_form.setLayout(
            14, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6
        )
        self.comment_save_structure_label = QtWidgets.QLabel(ObjectSettingsWidget)
        self.comment_save_structure_label.setObjectName("comment_save_structure_label")
        self.comment_download_form.setWidget(
            15, QtWidgets.QFormLayout.LabelRole, self.comment_save_structure_label
        )
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.comment_save_path_structure_line_edit = QtWidgets.QLineEdit(
            ObjectSettingsWidget
        )
        self.comment_save_path_structure_line_edit.setObjectName(
            "comment_save_path_structure_line_edit"
        )
        self.horizontalLayout_7.addWidget(self.comment_save_path_structure_line_edit)
        self.comment_save_structure_available_tokens_button = QtWidgets.QToolButton(
            ObjectSettingsWidget
        )
        self.comment_save_structure_available_tokens_button.setObjectName(
            "comment_save_structure_available_tokens_button"
        )
        self.horizontalLayout_7.addWidget(
            self.comment_save_structure_available_tokens_button
        )
        self.comment_download_form.setLayout(
            15, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7
        )
        self.verticalLayout.addLayout(self.comment_download_form)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ObjectSettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(ObjectSettingsWidget)

    def retranslateUi(self, ObjectSettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        ObjectSettingsWidget.setWindowTitle(
            _translate("ObjectSettingsWidget", "Settings")
        )
        self.label.setText(_translate("ObjectSettingsWidget", "Core Settings:"))
        self.enable_download_checkbox.setText(
            _translate("ObjectSettingsWidget", "Download Enabled")
        )
        self.label_19.setText(
            _translate("ObjectSettingsWidget", "Post Download Settings:")
        )
        self.label_30.setText(
            _translate("ObjectSettingsWidget", "Extract Self Post Content:")
        )
        self.label_15.setText(
            _translate("ObjectSettingsWidget", "Download Self Post Text:")
        )
        self.label_31.setText(
            _translate("ObjectSettingsWidget", "Self Post File Format:")
        )
        self.label_13.setText(_translate("ObjectSettingsWidget", "Download Videos:"))
        self.label_14.setText(_translate("ObjectSettingsWidget", "Download Images:"))
        self.label_29.setText(_translate("ObjectSettingsWidget", "Download Gifs:"))
        self.label_28.setText(_translate("ObjectSettingsWidget", "NSFW Filter:"))
        self.post_download_naming_label.setText(
            _translate("ObjectSettingsWidget", "Download Naming:")
        )
        self.post_download_naming_line_edit.setPlaceholderText(
            _translate("ObjectSettingsWidget", "----")
        )
        self.post_download_naming_available_tokens_button.setToolTip(
            _translate("ObjectSettingsWidget", "See available tokens")
        )
        self.post_download_naming_available_tokens_button.setText(
            _translate("ObjectSettingsWidget", "...")
        )
        self.post_save_structure_label.setText(
            _translate("ObjectSettingsWidget", "Save Path Structure:")
        )
        self.post_save_path_structure_line_edit.setPlaceholderText(
            _translate("ObjectSettingsWidget", "----")
        )
        self.post_save_structure_available_tokens_button.setToolTip(
            _translate("ObjectSettingsWidget", "See available tokens")
        )
        self.post_save_structure_available_tokens_button.setText(
            _translate("ObjectSettingsWidget", "...")
        )
        self.duplicate_controls_groupbox.setTitle(
            _translate("ObjectSettingsWidget", "Duplicate Controls")
        )
        self.avoid_duplicate_urls_label.setToolTip(
            _translate(
                "ObjectSettingsWidget",
                "<html><head/><body><p>The URL of each downloaded file is stored. If an extracted file has a matching URL in the database, it won’t be downloaded.</p></body></html>",
            )
        )
        self.avoid_duplicate_urls_label.setText(
            _translate("ObjectSettingsWidget", "Avoid Duplicates URLs:")
        )
        self.hash_content_label.setToolTip(
            _translate(
                "ObjectSettingsWidget",
                "<html><head/><body><p>When enabled, an MD5 hash is generated for each downloaded file and stored in the database. This helps detect duplicates, but may slightly slow down downloads. Some duplicate detection features will be unavailable if disabled.</p></body></html>",
            )
        )
        self.hash_content_label.setText(
            _translate("ObjectSettingsWidget", "Hash Content")
        )
        self.avoid_duplicates_checkbox.setToolTip(
            _translate(
                "ObjectSettingsWidget",
                "<html><head/><body><p>The URL of each downloaded file is stored. If an extracted file has a matching URL in the database, it won’t be downloaded.</p></body></html>",
            )
        )
        self.hash_content_checkbox.setToolTip(
            _translate(
                "ObjectSettingsWidget",
                "<html><head/><body><p>When checked, an MD5 hash will be generated for each downloaded file and stored in the database.  Some duplicate controls will not be available if this is disabled.  This may result in slightly slower downloads.  </p></body></html>",
            )
        )
        self.duplicate_control_method_combo_label.setToolTip(
            _translate(
                "ObjectSettingsWidget",
                "<html><head/><body><p>Dictates how duplicates are handled.</p></body></html>",
            )
        )
        self.duplicate_control_method_combo_label.setText(
            _translate("ObjectSettingsWidget", "Duplicate Control Method:")
        )
        self.duplicate_naming_method_label.setToolTip(
            _translate(
                "ObjectSettingsWidget",
                "<html><head/><body><p>When the duplicate control method is MOVE, this pattern will be used to rename duplicates. (Match to download naming to keep the original post name)</p></body></html>",
            )
        )
        self.duplicate_naming_method_label.setText(
            _translate("ObjectSettingsWidget", "Duplicate Naming Method:")
        )
        self.duplicate_naming_line_edit.setPlaceholderText(
            _translate("ObjectSettingsWidget", "----")
        )
        self.duplicate_naming_available_tokens_button.setToolTip(
            _translate("ObjectSettingsWidget", "See available tokens")
        )
        self.duplicate_naming_available_tokens_button.setText(
            _translate("ObjectSettingsWidget", "...")
        )
        self.duplicate_save_structure_label.setToolTip(
            _translate(
                "ObjectSettingsWidget",
                "<html><head/><body><p>When the duplicate control method is MOVE, this pattern will be used to structure the path the duplicates are moved to.</p></body></html>",
            )
        )
        self.duplicate_save_structure_label.setText(
            _translate("ObjectSettingsWidget", "Duplicate Path Structure")
        )
        self.duplicate_save_structure_line_edit.setPlaceholderText(
            _translate("ObjectSettingsWidget", "----")
        )
        self.duplicate_save_structure_available_tokens_button.setToolTip(
            _translate("ObjectSettingsWidget", "See available tokens")
        )
        self.duplicate_save_structure_available_tokens_button.setText(
            _translate("ObjectSettingsWidget", "...")
        )
        self.label_20.setText(
            _translate("ObjectSettingsWidget", "Comment Download Settings:")
        )
        self.label_32.setText(_translate("ObjectSettingsWidget", "Extract:"))
        self.label_22.setText(_translate("ObjectSettingsWidget", "Download:"))
        self.label_21.setText(_translate("ObjectSettingsWidget", "Download Links"))
        self.label_23.setText(_translate("ObjectSettingsWidget", "Comment Limit:"))
        self.comment_limit_spinbox.setToolTip(
            _translate(
                "ObjectSettingsWidget",
                "Only limits top level comment.  May pull more comments depending on replies",
            )
        )
        self.comment_limit_max_button.setText(_translate("ObjectSettingsWidget", "Max"))
        self.label_3.setText(_translate("ObjectSettingsWidget", "Comment Depth:"))
        self.comment_depth_max_button.setText(_translate("ObjectSettingsWidget", "Max"))
        self.label_4.setText(_translate("ObjectSettingsWidget", "Comment Reply Limit:"))
        self.comment_reply_max_button.setText(_translate("ObjectSettingsWidget", "Max"))
        self.label_2.setText(_translate("ObjectSettingsWidget", "Comment File Format:"))
        self.comment_download_naming_label.setText(
            _translate("ObjectSettingsWidget", "Download Naming:")
        )
        self.comment_download_naming_line_edit.setPlaceholderText(
            _translate("ObjectSettingsWidget", "----")
        )
        self.comment_download_naming_available_tokens_button.setToolTip(
            _translate("ObjectSettingsWidget", "See available tokens")
        )
        self.comment_download_naming_available_tokens_button.setText(
            _translate("ObjectSettingsWidget", "...")
        )
        self.comment_save_structure_label.setText(
            _translate("ObjectSettingsWidget", "Save Path Structure:")
        )
        self.comment_save_path_structure_line_edit.setPlaceholderText(
            _translate("ObjectSettingsWidget", "----")
        )
        self.comment_save_structure_available_tokens_button.setToolTip(
            _translate("ObjectSettingsWidget", "See available tokens")
        )
        self.comment_save_structure_available_tokens_button.setText(
            _translate("ObjectSettingsWidget", "...")
        )
