# Form implementation generated from reading ui file 'Resources/ui_files/downloader_for_reddit_gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1232, 836)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap("Resources/ui_files\\../images/RedditDownloaderIcon.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horz_splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.horz_splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horz_splitter.setObjectName("horz_splitter")
        self.object_tab_widget = QtWidgets.QTabWidget(parent=self.horz_splitter)
        self.object_tab_widget.setObjectName("object_tab_widget")
        self.user_tab = QtWidgets.QWidget()
        self.user_tab.setObjectName("user_tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.user_tab)
        self.verticalLayout.setSpacing(4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.user_list_search_edit = QtWidgets.QLineEdit(parent=self.user_tab)
        self.user_list_search_edit.setMinimumWidth(120)
        self.user_list_search_edit.setObjectName("user_list_search_edit")
        self.horizontalLayout_4.addWidget(self.user_list_search_edit)
        self.add_user_button = QtWidgets.QPushButton(parent=self.user_tab)
        self.add_user_button.setObjectName("add_user_button")
        self.horizontalLayout_4.addWidget(self.add_user_button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.user_list_view = QtWidgets.QTableView(parent=self.user_tab)
        self.user_list_view.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection
        )
        self.user_list_view.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.user_list_view.setSortingEnabled(True)
        self.user_list_view.setObjectName("user_list_view")
        self.user_list_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.user_list_view)
        self.user_lists_combo = QtWidgets.QComboBox(parent=self.user_tab)
        self.user_lists_combo.setObjectName("user_lists_combo")
        self.verticalLayout.addWidget(self.user_lists_combo)
        self.object_tab_widget.addTab(self.user_tab, "")
        self.subreddit_tab = QtWidgets.QWidget()
        self.subreddit_tab.setObjectName("subreddit_tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.subreddit_tab)
        self.verticalLayout_2.setSpacing(4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.subreddit_list_search_edit = QtWidgets.QLineEdit(parent=self.subreddit_tab)
        self.subreddit_list_search_edit.setMinimumWidth(120)
        self.subreddit_list_search_edit.setObjectName("subreddit_list_search_edit")
        self.horizontalLayout_5.addWidget(self.subreddit_list_search_edit)
        self.add_subreddit_button = QtWidgets.QPushButton(parent=self.subreddit_tab)
        self.add_subreddit_button.setObjectName("add_subreddit_button")
        self.horizontalLayout_5.addWidget(self.add_subreddit_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.subreddit_list_view = QtWidgets.QTableView(parent=self.subreddit_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subreddit_list_view.setFont(font)
        self.subreddit_list_view.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection
        )
        self.subreddit_list_view.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.subreddit_list_view.setSortingEnabled(True)
        self.subreddit_list_view.setObjectName("subreddit_list_view")
        self.subreddit_list_view.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.subreddit_list_view)
        self.subreddit_list_combo = QtWidgets.QComboBox(parent=self.subreddit_tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.subreddit_list_combo.setFont(font)
        self.subreddit_list_combo.setObjectName("subreddit_list_combo")
        self.verticalLayout_2.addWidget(self.subreddit_list_combo)
        self.object_tab_widget.addTab(self.subreddit_tab, "")
        self.layoutWidget = QtWidgets.QWidget(parent=self.horz_splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.download_button_layout = QtWidgets.QHBoxLayout()
        self.download_button_layout.setObjectName("download_button_layout")
        self.download_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.download_button.setFont(font)
        self.download_button.setObjectName("download_button")
        self.download_button_layout.addWidget(self.download_button)
        self.soft_stop_download_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.soft_stop_download_button.setFont(font)
        self.soft_stop_download_button.setObjectName("soft_stop_download_button")
        self.download_button_layout.addWidget(self.soft_stop_download_button)
        self.terminate_download_button = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.terminate_download_button.setObjectName("terminate_download_button")
        self.download_button_layout.addWidget(self.terminate_download_button)
        self.verticalLayout_3.addLayout(self.download_button_layout)
        self.line = QtWidgets.QFrame(parent=self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.output_list_view = QtWidgets.QListView(parent=self.layoutWidget)
        self.output_list_view.setStyleSheet(
            "QListView {\n"
            "    outline: 0;\n"
            "}\n"
            "\n"
            "QListView::item:hover {\n"
            "    background: white;\n"
            "}\n"
            "\n"
            "QListView::item:selected {\n"
            "    background: white;\n"
            "}\n"
            "\n"
            "QListView::item:active {\n"
            "    background: white;\n"
            "}"
        )
        self.output_list_view.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.output_list_view.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.NoSelection
        )
        self.output_list_view.setObjectName("output_list_view")
        self.verticalLayout_3.addWidget(self.output_list_view)
        self.verticalLayout_4.addWidget(self.horz_splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1232, 23))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(parent=self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.lists_menu = QtWidgets.QMenu(parent=self.menubar)
        self.lists_menu.setObjectName("lists_menu")
        self.help_menu = QtWidgets.QMenu(parent=self.menubar)
        self.help_menu.setObjectName("help_menu")
        self.menuDownload = QtWidgets.QMenu(parent=self.menubar)
        self.menuDownload.setObjectName("menuDownload")
        self.menuDatabase = QtWidgets.QMenu(parent=self.menubar)
        self.menuDatabase.setObjectName("menuDatabase")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.add_user_list_menu_item = QtGui.QAction(parent=MainWindow)
        self.add_user_list_menu_item.setObjectName("add_user_list_menu_item")
        self.add_subreddit_list_menu_item = QtGui.QAction(parent=MainWindow)
        self.add_subreddit_list_menu_item.setObjectName("add_subreddit_list_menu_item")
        self.file_save = QtGui.QAction(parent=MainWindow)
        self.file_save.setObjectName("file_save")
        self.remove_user_list_menu_item = QtGui.QAction(parent=MainWindow)
        self.remove_user_list_menu_item.setObjectName("remove_user_list_menu_item")
        self.remove_subreddit_list_menu_item = QtGui.QAction(parent=MainWindow)
        self.remove_subreddit_list_menu_item.setObjectName(
            "remove_subreddit_list_menu_item"
        )
        self.open_settings_menu_item = QtGui.QAction(parent=MainWindow)
        self.open_settings_menu_item.setObjectName("open_settings_menu_item")
        self.exit_menu_item = QtGui.QAction(parent=MainWindow)
        self.exit_menu_item.setObjectName("exit_menu_item")
        self.failed_download_view_menu_item = QtGui.QAction(parent=MainWindow)
        self.failed_download_view_menu_item.setObjectName(
            "failed_download_view_menu_item"
        )
        self.file_open_user_finder = QtGui.QAction(parent=MainWindow)
        self.file_open_user_finder.setObjectName("file_open_user_finder")
        self.download_session_menu_item = QtGui.QAction(parent=MainWindow)
        self.download_session_menu_item.setObjectName("download_session_menu_item")
        self.failed_extraction_view_menu_item = QtGui.QAction(parent=MainWindow)
        self.failed_extraction_view_menu_item.setObjectName(
            "failed_extraction_view_menu_item"
        )
        self.imgur_credit_dialog_menu_item = QtGui.QAction(parent=MainWindow)
        self.imgur_credit_dialog_menu_item.setObjectName(
            "imgur_credit_dialog_menu_item"
        )
        self.about_menu_item = QtGui.QAction(parent=MainWindow)
        self.about_menu_item.setObjectName("about_menu_item")
        self.file_user_list_count = QtGui.QAction(parent=MainWindow)
        self.file_user_list_count.setObjectName("file_user_list_count")
        self.file_subreddit_list_count = QtGui.QAction(parent=MainWindow)
        self.file_subreddit_list_count.setObjectName("file_subreddit_list_count")
        self.user_manual_menu_item = QtGui.QAction(parent=MainWindow)
        self.user_manual_menu_item.setObjectName("user_manual_menu_item")
        self.check_for_updates_menu_item = QtGui.QAction(parent=MainWindow)
        self.check_for_updates_menu_item.setObjectName("check_for_updates_menu_item")
        self.sort_list_by_name_menu_item = QtGui.QAction(parent=MainWindow)
        self.sort_list_by_name_menu_item.setCheckable(True)
        self.sort_list_by_name_menu_item.setObjectName("sort_list_by_name_menu_item")
        self.sort_list_by_date_added_menu_item = QtGui.QAction(parent=MainWindow)
        self.sort_list_by_date_added_menu_item.setCheckable(True)
        self.sort_list_by_date_added_menu_item.setObjectName(
            "sort_list_by_date_added_menu_item"
        )
        self.sort_list_by_post_count_menu_item = QtGui.QAction(parent=MainWindow)
        self.sort_list_by_post_count_menu_item.setCheckable(True)
        self.sort_list_by_post_count_menu_item.setObjectName(
            "sort_list_by_post_count_menu_item"
        )
        self.open_data_directory_menu_item = QtGui.QAction(parent=MainWindow)
        self.open_data_directory_menu_item.setObjectName(
            "open_data_directory_menu_item"
        )
        self.import_database_file_menu_item = QtGui.QAction(parent=MainWindow)
        self.import_database_file_menu_item.setObjectName(
            "import_database_file_menu_item"
        )
        self.ffmpeg_requirement_dialog_menu_item = QtGui.QAction(parent=MainWindow)
        self.ffmpeg_requirement_dialog_menu_item.setObjectName(
            "ffmpeg_requirement_dialog_menu_item"
        )
        self.download_user_list_menu_item = QtGui.QAction(parent=MainWindow)
        self.download_user_list_menu_item.setObjectName("download_user_list_menu_item")
        self.download_subreddit_list_menu_item = QtGui.QAction(parent=MainWindow)
        self.download_subreddit_list_menu_item.setObjectName(
            "download_subreddit_list_menu_item"
        )
        self.download_user_list_constrained_menu_item = QtGui.QAction(parent=MainWindow)
        self.download_user_list_constrained_menu_item.setObjectName(
            "download_user_list_constrained_menu_item"
        )
        self.run_unfinished_extractions_menu_item = QtGui.QAction(parent=MainWindow)
        self.run_unfinished_extractions_menu_item.setObjectName(
            "run_unfinished_extractions_menu_item"
        )
        self.run_unfinished_downloads_menu_item = QtGui.QAction(parent=MainWindow)
        self.run_unfinished_downloads_menu_item.setObjectName(
            "run_unfinished_downloads_menu_item"
        )
        self.sort_list_by_content_count_menu_item = QtGui.QAction(parent=MainWindow)
        self.sort_list_by_content_count_menu_item.setObjectName(
            "sort_list_by_content_count_menu_item"
        )
        self.sort_list_by_comment_count_menu_item = QtGui.QAction(parent=MainWindow)
        self.sort_list_by_comment_count_menu_item.setObjectName(
            "sort_list_by_comment_count_menu_item"
        )
        self.sort_list_by_date_created_menu_item = QtGui.QAction(parent=MainWindow)
        self.sort_list_by_date_created_menu_item.setObjectName(
            "sort_list_by_date_created_menu_item"
        )
        self.database_view_menu_item = QtGui.QAction(parent=MainWindow)
        self.database_view_menu_item.setObjectName("database_view_menu_item")
        self.download_sessions_view_menu_item = QtGui.QAction(parent=MainWindow)
        self.download_sessions_view_menu_item.setObjectName(
            "download_sessions_view_menu_item"
        )
        self.reddit_objects_view_menu_item = QtGui.QAction(parent=MainWindow)
        self.reddit_objects_view_menu_item.setObjectName(
            "reddit_objects_view_menu_item"
        )
        self.posts_view_menu_item = QtGui.QAction(parent=MainWindow)
        self.posts_view_menu_item.setObjectName("posts_view_menu_item")
        self.content_view_menu_item = QtGui.QAction(parent=MainWindow)
        self.content_view_menu_item.setObjectName("content_view_menu_item")
        self.comments_view_menu_item = QtGui.QAction(parent=MainWindow)
        self.comments_view_menu_item.setObjectName("comments_view_menu_item")
        self.statistics_view_menu_item = QtGui.QAction(parent=MainWindow)
        self.statistics_view_menu_item.setObjectName("statistics_view_menu_item")
        self.run_all_unfiinished_menu_item = QtGui.QAction(parent=MainWindow)
        self.run_all_unfiinished_menu_item.setObjectName(
            "run_all_unfiinished_menu_item"
        )
        self.export_user_list_menu_item = QtGui.QAction(parent=MainWindow)
        self.export_user_list_menu_item.setObjectName("export_user_list_menu_item")
        self.export_subreddit_list_menu_item = QtGui.QAction(parent=MainWindow)
        self.export_subreddit_list_menu_item.setObjectName(
            "export_subreddit_list_menu_item"
        )
        self.command_line_options_menu_item = QtGui.QAction(parent=MainWindow)
        self.command_line_options_menu_item.setObjectName(
            "command_line_options_menu_item"
        )
        self.minimize_to_tray_menu_item = QtGui.QAction(parent=MainWindow)
        self.minimize_to_tray_menu_item.setObjectName("minimize_to_tray_menu_item")
        self.connect_reddit_account_menu_item = QtGui.QAction(parent=MainWindow)
        self.connect_reddit_account_menu_item.setObjectName(
            "connect_reddit_account_menu_item"
        )
        self.file_menu.addAction(self.open_settings_menu_item)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.connect_reddit_account_menu_item)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.open_data_directory_menu_item)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.minimize_to_tray_menu_item)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.exit_menu_item)
        self.lists_menu.addAction(self.add_user_list_menu_item)
        self.lists_menu.addAction(self.add_subreddit_list_menu_item)
        self.lists_menu.addSeparator()
        self.lists_menu.addAction(self.remove_user_list_menu_item)
        self.lists_menu.addAction(self.remove_subreddit_list_menu_item)
        self.lists_menu.addSeparator()
        self.lists_menu.addAction(self.export_user_list_menu_item)
        self.lists_menu.addAction(self.export_subreddit_list_menu_item)
        self.help_menu.addAction(self.imgur_credit_dialog_menu_item)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.user_manual_menu_item)
        self.help_menu.addAction(self.ffmpeg_requirement_dialog_menu_item)
        self.help_menu.addAction(self.command_line_options_menu_item)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.check_for_updates_menu_item)
        self.help_menu.addSeparator()
        self.help_menu.addAction(self.about_menu_item)
        self.menuDownload.addAction(self.download_user_list_menu_item)
        self.menuDownload.addAction(self.download_subreddit_list_menu_item)
        self.menuDownload.addAction(self.download_user_list_constrained_menu_item)
        self.menuDownload.addSeparator()
        self.menuDownload.addAction(self.run_unfinished_extractions_menu_item)
        self.menuDownload.addAction(self.run_unfinished_downloads_menu_item)
        self.menuDownload.addAction(self.run_all_unfiinished_menu_item)
        self.menuDatabase.addAction(self.database_view_menu_item)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.download_sessions_view_menu_item)
        self.menuDatabase.addAction(self.reddit_objects_view_menu_item)
        self.menuDatabase.addAction(self.posts_view_menu_item)
        self.menuDatabase.addAction(self.content_view_menu_item)
        self.menuDatabase.addAction(self.comments_view_menu_item)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.failed_extraction_view_menu_item)
        self.menuDatabase.addAction(self.failed_download_view_menu_item)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.statistics_view_menu_item)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.lists_menu.menuAction())
        self.menubar.addAction(self.menuDatabase.menuAction())
        self.menubar.addAction(self.menuDownload.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Downloader for Reddit"))
        self.user_list_search_edit.setPlaceholderText(
            _translate("MainWindow", "Search users")
        )
        self.add_user_button.setToolTip(_translate("MainWindow", "Add User"))
        self.add_user_button.setText(_translate("MainWindow", "Add"))
        self.user_lists_combo.setToolTip(_translate("MainWindow", "Current user list"))
        self.object_tab_widget.setTabText(
            self.object_tab_widget.indexOf(self.user_tab),
            _translate("MainWindow", "Users"),
        )
        self.subreddit_list_search_edit.setPlaceholderText(
            _translate("MainWindow", "Search subreddits")
        )
        self.add_subreddit_button.setToolTip(_translate("MainWindow", "Add Subreddit"))
        self.add_subreddit_button.setText(_translate("MainWindow", "Add"))
        self.subreddit_list_combo.setToolTip(
            _translate("MainWindow", "Current subreddit list")
        )
        self.object_tab_widget.setTabText(
            self.object_tab_widget.indexOf(self.subreddit_tab),
            _translate("MainWindow", "Subreddits"),
        )
        self.download_button.setToolTip(
            _translate("MainWindow", "Download selected user or subreddit list")
        )
        self.download_button.setText(_translate("MainWindow", "Download"))
        self.soft_stop_download_button.setToolTip(
            _translate(
                "MainWindow",
                "Stops the current download, but allows in progress downloads to finish",
            )
        )
        self.soft_stop_download_button.setText(
            _translate("MainWindow", "Schedule Stop Download")
        )
        self.terminate_download_button.setToolTip(
            _translate(
                "MainWindow",
                "Stops the download immediately and terminates in progress downloads (may result in corrupted files for downloads that were not complete)",
            )
        )
        self.terminate_download_button.setText(
            _translate("MainWindow", "Terminate Download")
        )
        self.file_menu.setTitle(_translate("MainWindow", "File"))
        self.lists_menu.setTitle(_translate("MainWindow", "Lists"))
        self.help_menu.setTitle(_translate("MainWindow", "Help"))
        self.menuDownload.setTitle(_translate("MainWindow", "Download"))
        self.menuDatabase.setTitle(_translate("MainWindow", "Database"))
        self.add_user_list_menu_item.setText(_translate("MainWindow", "Add User List"))
        self.add_subreddit_list_menu_item.setText(
            _translate("MainWindow", "Add Subreddit List")
        )
        self.file_save.setText(_translate("MainWindow", "Save"))
        self.remove_user_list_menu_item.setText(
            _translate("MainWindow", "Remove User List")
        )
        self.remove_subreddit_list_menu_item.setText(
            _translate("MainWindow", "Remove Subreddit List")
        )
        self.open_settings_menu_item.setText(_translate("MainWindow", "Settings"))
        self.exit_menu_item.setText(_translate("MainWindow", "Exit"))
        self.failed_download_view_menu_item.setText(
            _translate("MainWindow", "Failed Download")
        )
        self.failed_download_view_menu_item.setToolTip(
            _translate(
                "MainWindow",
                "Display the failed download list for the last download session",
            )
        )
        self.file_open_user_finder.setText(_translate("MainWindow", "Open User Finder"))
        self.download_session_menu_item.setText(
            _translate("MainWindow", "Download Sessions")
        )
        self.failed_extraction_view_menu_item.setText(
            _translate("MainWindow", "Failed Extractions")
        )
        self.imgur_credit_dialog_menu_item.setText(
            _translate("MainWindow", "Imgur Credits")
        )
        self.about_menu_item.setText(_translate("MainWindow", "About"))
        self.file_user_list_count.setText(_translate("MainWindow", "User List Count:"))
        self.file_subreddit_list_count.setText(
            _translate("MainWindow", "Subreddit List Count:")
        )
        self.user_manual_menu_item.setText(_translate("MainWindow", "User Manual"))
        self.check_for_updates_menu_item.setText(
            _translate("MainWindow", "Check For Update")
        )
        self.sort_list_by_name_menu_item.setText(_translate("MainWindow", "Name"))
        self.sort_list_by_date_added_menu_item.setText(
            _translate("MainWindow", "Date Added")
        )
        self.sort_list_by_post_count_menu_item.setText(
            _translate("MainWindow", "Post Count")
        )
        self.open_data_directory_menu_item.setText(
            _translate("MainWindow", "Open Data Directory")
        )
        self.import_database_file_menu_item.setText(
            _translate("MainWindow", "Import Save File")
        )
        self.ffmpeg_requirement_dialog_menu_item.setText(
            _translate("MainWindow", "FFmpeg Requirement")
        )
        self.download_user_list_menu_item.setText(
            _translate("MainWindow", "Download User List")
        )
        self.download_subreddit_list_menu_item.setText(
            _translate("MainWindow", "Download Subreddit List")
        )
        self.download_user_list_constrained_menu_item.setText(
            _translate("MainWindow", "Download User List Constrained")
        )
        self.download_user_list_constrained_menu_item.setToolTip(
            _translate(
                "MainWindow",
                "<html><head/><body><p>Download user list, but only extract posts made to subreddits in the subreddit list</p></body></html>",
            )
        )
        self.run_unfinished_extractions_menu_item.setText(
            _translate("MainWindow", "Run Unfinished Extractions")
        )
        self.run_unfinished_downloads_menu_item.setText(
            _translate("MainWindow", "Run Unfinished Downloads")
        )
        self.sort_list_by_content_count_menu_item.setText(
            _translate("MainWindow", "Content Count")
        )
        self.sort_list_by_comment_count_menu_item.setText(
            _translate("MainWindow", "Comment Count")
        )
        self.sort_list_by_date_created_menu_item.setText(
            _translate("MainWindow", "Date Created")
        )
        self.sort_list_by_date_created_menu_item.setToolTip(
            _translate(
                "MainWindow",
                "Sort reddit objects by the date that the item was created on reddit",
            )
        )
        self.database_view_menu_item.setText(_translate("MainWindow", "Database View"))
        self.download_sessions_view_menu_item.setText(
            _translate("MainWindow", "Download Sessions")
        )
        self.reddit_objects_view_menu_item.setText(
            _translate("MainWindow", "Reddit Objects")
        )
        self.posts_view_menu_item.setText(_translate("MainWindow", "Posts"))
        self.content_view_menu_item.setText(_translate("MainWindow", "Content"))
        self.comments_view_menu_item.setText(_translate("MainWindow", "Comments"))
        self.statistics_view_menu_item.setText(_translate("MainWindow", "Statistics"))
        self.run_all_unfiinished_menu_item.setText(
            _translate("MainWindow", "Run All Unfinished")
        )
        self.export_user_list_menu_item.setText(
            _translate("MainWindow", "Export User List")
        )
        self.export_subreddit_list_menu_item.setText(
            _translate("MainWindow", "Export Subreddit List")
        )
        self.command_line_options_menu_item.setText(
            _translate("MainWindow", "Command Line Options")
        )
        self.minimize_to_tray_menu_item.setText(
            _translate("MainWindow", "Minimize To Tray")
        )
        self.connect_reddit_account_menu_item.setText(
            _translate("MainWindow", "Connect Reddit Account")
        )
