# Form implementation generated from reading ui file 'Resources/ui_files/download_sessions_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_DownloadSessionDialog:
    def setupUi(self, DownloadSessionDialog):
        DownloadSessionDialog.setObjectName("DownloadSessionDialog")
        DownloadSessionDialog.resize(1689, 919)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(DownloadSessionDialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.show_reddit_objects_checkbox = QtWidgets.QCheckBox(
            parent=DownloadSessionDialog
        )
        self.show_reddit_objects_checkbox.setObjectName("show_reddit_objects_checkbox")
        self.horizontalLayout.addWidget(self.show_reddit_objects_checkbox)
        self.show_posts_checkbox = QtWidgets.QCheckBox(parent=DownloadSessionDialog)
        self.show_posts_checkbox.setObjectName("show_posts_checkbox")
        self.horizontalLayout.addWidget(self.show_posts_checkbox)
        self.show_content_checkbox = QtWidgets.QCheckBox(parent=DownloadSessionDialog)
        self.show_content_checkbox.setObjectName("show_content_checkbox")
        self.horizontalLayout.addWidget(self.show_content_checkbox)
        self.show_comments_checkbox = QtWidgets.QCheckBox(parent=DownloadSessionDialog)
        self.show_comments_checkbox.setObjectName("show_comments_checkbox")
        self.horizontalLayout.addWidget(self.show_comments_checkbox)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(parent=DownloadSessionDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.download_session_widget = QtWidgets.QWidget(parent=self.splitter)
        self.download_session_widget.setObjectName("download_session_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.download_session_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.download_session_list_view = QtWidgets.QListView(
            parent=self.download_session_widget
        )
        self.download_session_list_view.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.download_session_list_view.setObjectName("download_session_list_view")
        self.verticalLayout.addWidget(self.download_session_list_view)
        self.reddit_object_widget = QtWidgets.QWidget(parent=self.splitter)
        self.reddit_object_widget.setObjectName("reddit_object_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.reddit_object_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.reddit_object_list_view = QtWidgets.QListView(
            parent=self.reddit_object_widget
        )
        self.reddit_object_list_view.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.reddit_object_list_view.setObjectName("reddit_object_list_view")
        self.verticalLayout_2.addWidget(self.reddit_object_list_view)
        self.post_widget = QtWidgets.QWidget(parent=self.splitter)
        self.post_widget.setObjectName("post_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.post_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.post_splitter = QtWidgets.QSplitter(parent=self.post_widget)
        self.post_splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.post_splitter.setObjectName("post_splitter")
        self.post_table_view = QtWidgets.QTableView(parent=self.post_splitter)
        self.post_table_view.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored
        )
        self.post_table_view.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.post_table_view.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.SingleSelection
        )
        self.post_table_view.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.post_table_view.setShowGrid(False)
        self.post_table_view.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.post_table_view.setObjectName("post_table_view")
        self.post_table_view.horizontalHeader().setCascadingSectionResizes(False)
        self.post_text_browser = QtWidgets.QTextBrowser(parent=self.post_splitter)
        self.post_text_browser.setOpenExternalLinks(True)
        self.post_text_browser.setObjectName("post_text_browser")
        self.verticalLayout_3.addWidget(self.post_splitter)
        self.content_widget = QtWidgets.QWidget(parent=self.splitter)
        self.content_widget.setObjectName("content_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.content_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.content_list_view = QtWidgets.QListView(parent=self.content_widget)
        self.content_list_view.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.content_list_view.setIconSize(QtCore.QSize(0, 0))
        self.content_list_view.setFlow(QtWidgets.QListView.Flow.LeftToRight)
        self.content_list_view.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        self.content_list_view.setLayoutMode(QtWidgets.QListView.LayoutMode.Batched)
        self.content_list_view.setGridSize(QtCore.QSize(0, 0))
        self.content_list_view.setViewMode(QtWidgets.QListView.ViewMode.IconMode)
        self.content_list_view.setBatchSize(10)
        self.content_list_view.setWordWrap(True)
        self.content_list_view.setObjectName("content_list_view")
        self.verticalLayout_4.addWidget(self.content_list_view)
        self.comment_widget = QtWidgets.QWidget(parent=self.splitter)
        self.comment_widget.setObjectName("comment_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.comment_widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.comment_tree_view = QtWidgets.QTreeView(parent=self.comment_widget)
        self.comment_tree_view.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.comment_tree_view.setObjectName("comment_tree_view")
        self.verticalLayout_5.addWidget(self.comment_tree_view)
        self.verticalLayout_6.addWidget(self.splitter)

        self.retranslateUi(DownloadSessionDialog)
        QtCore.QMetaObject.connectSlotsByName(DownloadSessionDialog)

    def retranslateUi(self, DownloadSessionDialog):
        _translate = QtCore.QCoreApplication.translate
        DownloadSessionDialog.setWindowTitle(
            _translate("DownloadSessionDialog", "Download Sessions")
        )
        self.show_reddit_objects_checkbox.setText(
            _translate("DownloadSessionDialog", "Show reddit objects")
        )
        self.show_posts_checkbox.setText(
            _translate("DownloadSessionDialog", "Show posts")
        )
        self.show_content_checkbox.setText(
            _translate("DownloadSessionDialog", "Show content")
        )
        self.show_comments_checkbox.setText(
            _translate("DownloadSessionDialog", "Show comments")
        )
