# Form implementation generated from reading ui file 'Resources/ui_files/database_views/filter_widget.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_FilterWidget:
    def setupUi(self, FilterWidget):
        FilterWidget.setObjectName("FilterWidget")
        FilterWidget.resize(350, 850)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FilterWidget.sizePolicy().hasHeightForWidth())
        FilterWidget.setSizePolicy(sizePolicy)
        FilterWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        FilterWidget.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(FilterWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filter_input_widget = FilterInputWidget(parent=FilterWidget)
        self.filter_input_widget.setObjectName("filter_input_widget")
        self.verticalLayout.addWidget(self.filter_input_widget)
        self.filter_box_list_widget = QtWidgets.QListWidget(parent=FilterWidget)
        self.filter_box_list_widget.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded
        )
        self.filter_box_list_widget.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored
        )
        self.filter_box_list_widget.setEditTriggers(
            QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers
        )
        self.filter_box_list_widget.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection
        )
        self.filter_box_list_widget.setMovement(QtWidgets.QListView.Movement.Static)
        self.filter_box_list_widget.setFlow(QtWidgets.QListView.Flow.TopToBottom)
        self.filter_box_list_widget.setProperty("isWrapping", True)
        self.filter_box_list_widget.setResizeMode(QtWidgets.QListView.ResizeMode.Fixed)
        self.filter_box_list_widget.setLayoutMode(
            QtWidgets.QListView.LayoutMode.Batched
        )
        self.filter_box_list_widget.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.filter_box_list_widget.setUniformItemSizes(False)
        self.filter_box_list_widget.setBatchSize(1)
        self.filter_box_list_widget.setWordWrap(False)
        self.filter_box_list_widget.setSelectionRectVisible(False)
        self.filter_box_list_widget.setObjectName("filter_box_list_widget")
        self.verticalLayout.addWidget(self.filter_box_list_widget)

        self.retranslateUi(FilterWidget)
        QtCore.QMetaObject.connectSlotsByName(FilterWidget)

    def retranslateUi(self, FilterWidget):
        _translate = QtCore.QCoreApplication.translate
        FilterWidget.setWindowTitle(_translate("FilterWidget", "Filter"))


from DownloaderForReddit.gui.database_views.filter_input_widget import FilterInputWidget
