# Form implementation generated from reading ui file 'Resources/ui_files/settings/quick_filter_settings_widget.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_QuickFilterSettingsWidget:
    def setupUi(self, QuickFilterSettingsWidget):
        QuickFilterSettingsWidget.setObjectName("QuickFilterSettingsWidget")
        QuickFilterSettingsWidget.resize(906, 709)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(QuickFilterSettingsWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(parent=QuickFilterSettingsWidget)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(parent=self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_new_quick_filter_button = QtWidgets.QPushButton(parent=self.widget)
        self.add_new_quick_filter_button.setObjectName("add_new_quick_filter_button")
        self.verticalLayout_2.addWidget(self.add_new_quick_filter_button)
        self.name_list_widget = QtWidgets.QListWidget(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.name_list_widget.sizePolicy().hasHeightForWidth()
        )
        self.name_list_widget.setSizePolicy(sizePolicy)
        self.name_list_widget.setObjectName("name_list_widget")
        self.verticalLayout_2.addWidget(self.name_list_widget)
        self.widget1 = QtWidgets.QWidget(parent=self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filter_input_widget = FilterInputWidget(parent=self.widget1)
        self.filter_input_widget.setObjectName("filter_input_widget")
        self.verticalLayout.addWidget(self.filter_input_widget)
        self.filter_list_widget = QtWidgets.QListWidget(parent=self.widget1)
        self.filter_list_widget.setMovement(QtWidgets.QListView.Movement.Static)
        self.filter_list_widget.setLayoutMode(QtWidgets.QListView.LayoutMode.Batched)
        self.filter_list_widget.setViewMode(QtWidgets.QListView.ViewMode.ListMode)
        self.filter_list_widget.setBatchSize(5)
        self.filter_list_widget.setObjectName("filter_list_widget")
        self.verticalLayout.addWidget(self.filter_list_widget)
        self.verticalLayout_3.addWidget(self.splitter)

        self.retranslateUi(QuickFilterSettingsWidget)
        QtCore.QMetaObject.connectSlotsByName(QuickFilterSettingsWidget)

    def retranslateUi(self, QuickFilterSettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        QuickFilterSettingsWidget.setWindowTitle(
            _translate("QuickFilterSettingsWidget", "Quick Filter Settings")
        )
        self.add_new_quick_filter_button.setText(
            _translate("QuickFilterSettingsWidget", "Add Quick Filter")
        )


from DownloaderForReddit.gui.database_views.filter_input_widget import FilterInputWidget
